version: '3.3'
services:
  debian:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: ${USER}
        uid: ${UID}
        group: ${GROUP}
        gid: ${GID}
        SSH_PUBLIC_KEY: ${SSH_PUBLIC_KEY}
    container_name: pennix_debian_workspace
    network_mode: host
    hostname: ${HOSTNAME}
    ports:
      - "2222:2222"
    volumes:
      - ${HOST_HOME_VOLUME}:/home/${USER}
    tty: true
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
